### PR TITLE
ENH: add standard codes to describe measurements

### PR DESCRIPTION
**Pull request by fedorov**
Also initialize quantity and units from the scalar volume being analyzed. Note
that this approach is error prone, since it cannot be guaranteed that the
scalar volume on the parameter node will be the same between the time
measurements are calculated, and the time when the getInfo is called. It is
also not guaranteed that scalar volume parameter is populated at the time
getInfo is called. We should probably initialize info at the time measurements
are calculated.

### CODE REVIEW

**Comment by fedorov** [comment]
@chribaue thanks for merging, but please let me know your thoughts on:

> Note that this approach is error prone, since it cannot be guaranteed that the
scalar volume on the parameter node will be the same between the time
measurements are calculated, and the time when the getInfo is called. It is
also not guaranteed that scalar volume parameter is populated at the time
getInfo is called. We should probably initialize info at the time measurements
are calculated.

**Comment by chribaue** [comment]
@fedorov I didn't consider that a user might change the input data while calculating image statistics.
>  We should probably initialize info at the time measurements
are calculated

It should be easy to do that. I can store the measurement info the same way I currently store the measurements themselves.

**Comment by fedorov** [comment]
> I didn't consider that a user might change the input data while calculating image statistics.

Well, my point is that this functionality can also be used via API. getInfo can potentially be called at any time, and there is nothing that attaches it to the parameter node at the time measurements were computed. Perhaps getMeasurementInfo should take the parameter node as an argument?

**Comment by chribaue** [comment]
Well, if the user changes the scalar volume node reference in the parameter node before calling getMeasurementInfo, then I guess the user is interested in the measurement meta information of the new volume node.

I thought your concern is that a user might do calculations on scalar volume node A, and then somehow switches to scalar volume node B, before obtaining the measurement meta information for node A. Then the measurements and their meta data would not necessarily match.

**Comment by chribaue** [comment]
@fedorov I forgot before: Thank you for the adding the dicom codes!

**Comment by fedorov** [comment]
No problem. I think if you store the info the same way you store measurements at the time they are calculated, this should be helpful.

**Comment by chribaue** [comment]
Okay, then I'll make this change

**Comment by che85** [comment]
I am getting some errors when starting slicer with this commit. 

```
Number of registered modules: 113 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/christian/sources/py/Reporting/QuantitativeReporting.py", line 24, in <module>
    from SegmentStatistics import SegmentStatisticsLogic
  File "/Users/christian/sources/cpp/Slicer/Build/Slicer-build/lib/Slicer-4.7/qt-scripted-modules/SegmentStatistics.py", line 4, in <module>
    from SegmentStatisticsCalculators import *
  File "/Users/christian/sources/cpp/Slicer/Build/Slicer-build/lib/Slicer-4.7/qt-scripted-modules/SegmentStatisticsCalculators/__init__.py", line 3, in <module>
    from ScalarVolumeSegmentStatisticsCalculator import *
  File "/Users/christian/sources/cpp/Slicer/Build/Slicer-build/lib/Slicer-4.7/qt-scripted-modules/SegmentStatisticsCalculators/ScalarVolumeSegmentStatisticsCalculator.py", line 152
    "DICOM.QuantityCode": scalarVolumeQuantity.GetAsString(), \
                       ^
SyntaxError: invalid syntax
loadSourceAsModule - Failed to load file "/Users/christian/sources/py/Reporting/QuantitativeReporting.py"  as module "QuantitativeReporting" ! 
Fail to instantiate module  "QuantitativeReporting" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/christian/sources/cpp/Slicer/Build/Slicer-build/lib/Slicer-4.7/qt-scripted-modules/SegmentStatistics.py", line 4, in <module>
    from SegmentStatisticsCalculators import *
  File "/Users/christian/sources/cpp/Slicer/Build/Slicer-build/lib/Slicer-4.7/qt-scripted-modules/SegmentStatisticsCalculators/__init__.py", line 3, in <module>
    from ScalarVolumeSegmentStatisticsCalculator import *
  File "/Users/christian/sources/cpp/Slicer/Build/Slicer-build/lib/Slicer-4.7/qt-scripted-modules/SegmentStatisticsCalculators/ScalarVolumeSegmentStatisticsCalculator.py", line 152
    "DICOM.QuantityCode": scalarVolumeQuantity.GetAsString(), \
                       ^
SyntaxError: invalid syntax
loadSourceAsModule - Failed to load file "/Users/christian/sources/cpp/Slicer/Build/Slicer-build/lib/Slicer-4.7/qt-scripted-modules/SegmentStatistics.py"  as module "SegmentStatistics" ! 
Fail to instantiate module  "SegmentStatistics" 
```

Will fix this and create a new PR

**Comment by che85** [comment]
@chribaue Can you do me a favor and rebase this branch to current Slicer master?

**Pull request merged**
